# Use a Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install psycopg2 along with other project dependencies
RUN pip install --no-cache-dir -r requirements.txt psycopg2-binary

# Copy the rest of the project files to the working directory
COPY . .

# Set the command to run the Flask application
CMD ["python3", "models.py"]
